//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockTracker.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RockTracker.Api.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key authentication is not configured..
        /// </summary>
        internal static string ApiKeyNotConfiguredDetail {
            get {
                return ResourceManager.GetString("ApiKeyNotConfiguredDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key authentication is enabled but no key is configured under &apos;Authentication:ApiKey&apos;..
        /// </summary>
        internal static string ApiKeyNotConfiguredLog {
            get {
                return ResourceManager.GetString("ApiKeyNotConfiguredLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid X-Api-Key header is required..
        /// </summary>
        internal static string ApiKeyRequiredDetail {
            get {
                return ResourceManager.GetString("ApiKeyRequiredDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career rocks require a note explaining why this matters..
        /// </summary>
        internal static string CareerNoteRule {
            get {
                return ResourceManager.GetString("CareerNoteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category must be one of: Revenue, Health, Career, Other.
        /// </summary>
        internal static string CategoryMustBeAllowed {
            get {
                return ResourceManager.GetString("CategoryMustBeAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is required. Allowed: Revenue, Health, Career, Other.
        /// </summary>
        internal static string CategoryRequired {
            get {
                return ResourceManager.GetString("CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category-specific validation failed..
        /// </summary>
        internal static string CategoryValidationFailed {
            get {
                return ResourceManager.GetString("CategoryValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DueDate must be in the future.
        /// </summary>
        internal static string DueDateMustBeFuture {
            get {
                return ResourceManager.GetString("DueDateMustBeFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DueDate is required..
        /// </summary>
        internal static string DueDateRequired {
            get {
                return ResourceManager.GetString("DueDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health rocks must have a title with at least 10 characters..
        /// </summary>
        internal static string HealthTitleRule {
            get {
                return ResourceManager.GetString("HealthTitleRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberId is required..
        /// </summary>
        internal static string MemberIdRequired {
            get {
                return ResourceManager.GetString("MemberIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No external member found for member id.
        /// </summary>
        internal static string MemberNotFoundDetail {
            get {
                return ResourceManager.GetString("MemberNotFoundDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Not Found.
        /// </summary>
        internal static string MemberNotFoundTitle {
            get {
                return ResourceManager.GetString("MemberNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected request to {Path} due to missing or invalid API key..
        /// </summary>
        internal static string RejectedRequestLog {
            get {
                return ResourceManager.GetString("RejectedRequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue rocks must have a due date within the current quarter..
        /// </summary>
        internal static string RevenueDueDateRule {
            get {
                return ResourceManager.GetString("RevenueDueDateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Misconfigured.
        /// </summary>
        internal static string ServerMisconfiguredTitle {
            get {
                return ResourceManager.GetString("ServerMisconfiguredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is required. Allowed: pending, completed, missed.
        /// </summary>
        internal static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string UnauthorizedTitle {
            get {
                return ResourceManager.GetString("UnauthorizedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        internal static string UnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("UnexpectedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception caught by global middleware.
        /// </summary>
        internal static string UnhandledExceptionLog {
            get {
                return ResourceManager.GetString("UnhandledExceptionLog", resourceCulture);
            }
        }
    }
}
